### PR TITLE
Add analytics to the portal

### LINKED ISSUE #447: Add tracking to portal
Need to link with @dvnahuel to discuss what metrics we should be collecting from the portal app

### PR DESCRIPTION
**Pull request by gndelia**
### Description

This PR adds Umami to track analytics. [umami-analytics-next](https://www.npmjs.com/package/umami-analytics-next) was published as part of this PR.

`NEXT_PUBLIC_ANALYTICS_URL` and `NEXT_PUBLIC_ANALYTICS_WEBSITE_ID`  were set on Github (they are only enabled for prod)

### Screenshots

No visible changes to the user

### Related issue(s)

Closes #447 

### Checklist

- [x] Manual testing passed.
- [ ] Automated tests added, or N/A.
- [ ] Documentation updated, or N/A.
- [x] Environment variables set in CI, or N/A.

### CODE REVIEW

**Review by gabmontes — DISMISSED** [review]
uACK

**Comment by gndelia** [comment]
I forgot, I need to allow the script to load (considering security headers, as the script is on an external domain )

**Comment by gndelia** [comment]
Added [7b721ba](https://github.com/hemilabs/ui-monorepo/pull/606/commits/7b721ba0a74bbc0341d9b9263a886577efca8e4c) in which the domain where the analytics script lives is added to the security headers

**Review by gabmontes — APPROVED** [review]
uACK

**Review by ArturDolzan — APPROVED** [review]

**Pull request merged**
